# GitHub Sponsors
# github: [username]

# 其他赞助平台
# patreon: # 替换为你的 Patreon 用户名
# open_collective: # 替换为你的 Open Collective 名称
# ko_fi: # 替换为你的 Ko-fi 用户名
# tidelift: # 替换为你的 Tidelift 平台/包名
# community_bridge: # 替换为你的 Community Bridge 项目名
# liberapay: # 替换为你的 Liberapay 用户名
# issuehunt: # 替换为你的 IssueHunt 用户名
# otechie: # 替换为你的 Otechie 用户名
# lfx_crowdfunding: # 替换为你的 LFX Crowdfunding 项目名
# polar: # 替换为你的 Polar 用户名
# buy_me_a_coffee: # 替换为你的 Buy Me a Coffee 用户名

# 自定义赞助链接
custom: ['https://github.com/sponsors']
