import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Svelte Signals 代码实验室","description":"3个完整可运行的 SvelteKit 项目：TODO应用、博客平台、Dashboard面板","frontmatter":{"title":"Svelte Signals 代码实验室","description":"3个完整可运行的 SvelteKit 项目：TODO应用、博客平台、Dashboard面板"},"headers":[],"relativePath":"code-lab/svelte-signals-lab.md","filePath":"code-lab/svelte-signals-lab.md","lastUpdated":1777692261000}');
const _sfc_main = { name: "code-lab/svelte-signals-lab.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="svelte-signals-代码实验室" tabindex="-1">Svelte Signals 代码实验室 <a class="header-anchor" href="#svelte-signals-代码实验室" aria-label="Permalink to &quot;Svelte Signals 代码实验室&quot;">​</a></h1><blockquote><p>3 个完整可运行的 Svelte/SvelteKit 项目，覆盖从基础到进阶的全栈开发</p></blockquote><h2 id="实验室概览" tabindex="-1">实验室概览 <a class="header-anchor" href="#实验室概览" aria-label="Permalink to &quot;实验室概览&quot;">​</a></h2><table tabindex="0"><thead><tr><th>项目</th><th style="${ssrRenderStyle({ "text-align": "center" })}">难度</th><th>对应专题</th><th>技术栈</th><th>学习重点</th></tr></thead><tbody><tr><td><strong>01-TODO 应用</strong></td><td style="${ssrRenderStyle({ "text-align": "center" })}">🌿</td><td>02, 12, 13</td><td>Svelte 5 + Vite</td><td>Runes、组件交互、状态管理</td></tr><tr><td><strong>02-博客平台</strong></td><td style="${ssrRenderStyle({ "text-align": "center" })}">🌳</td><td>03, 04, 18</td><td>SvelteKit 2 + TypeScript</td><td>路由、Form Actions、API、SSR</td></tr><tr><td><strong>03-Dashboard</strong></td><td style="${ssrRenderStyle({ "text-align": "center" })}">🌳</td><td>13, 14, 15</td><td>Svelte 5 + D3.js</td><td>Action、数据可视化、实时更新</td></tr></tbody></table><h2 id="_01-todo-应用" tabindex="-1">01-TODO 应用 <a class="header-anchor" href="#_01-todo-应用" aria-label="Permalink to &quot;01-TODO 应用&quot;">​</a></h2><h3 id="项目简介" tabindex="-1">项目简介 <a class="header-anchor" href="#项目简介" aria-label="Permalink to &quot;项目简介&quot;">​</a></h3><p>基础 TODO 应用，覆盖 Svelte 5 核心概念。</p><h3 id="技术栈" tabindex="-1">技术栈 <a class="header-anchor" href="#技术栈" aria-label="Permalink to &quot;技术栈&quot;">​</a></h3><ul><li>Svelte 5.53.x</li><li>Vite 6.3</li><li>TypeScript 5.8</li><li>Vitest + Playwright</li></ul><h3 id="核心功能" tabindex="-1">核心功能 <a class="header-anchor" href="#核心功能" aria-label="Permalink to &quot;核心功能&quot;">​</a></h3><ul><li>✅ $state 管理任务列表</li><li>✅ $derived 计算完成统计</li><li>✅ $effect 本地存储持久化</li><li>✅ 组件拆分（TodoItem / TodoFilter）</li><li>✅ 过渡动画（fade/slide）</li><li>✅ 响应式筛选（全部/未完成/已完成）</li></ul><h3 id="文件结构" tabindex="-1">文件结构 <a class="header-anchor" href="#文件结构" aria-label="Permalink to &quot;文件结构&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>01-todo-app/</span></span>
<span class="line"><span>├── src/routes/+page.svelte      # 主页面</span></span>
<span class="line"><span>├── src/routes/TodoItem.svelte   # 单个任务组件</span></span>
<span class="line"><span>├── src/routes/TodoFilter.svelte # 筛选组件</span></span>
<span class="line"><span>├── src/lib/stores/todoStore.ts  # 共享状态</span></span>
<span class="line"><span>├── tests/                       # 测试</span></span>
<span class="line"><span>└── Dockerfile                   # 部署</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="运行方式" tabindex="-1">运行方式 <a class="header-anchor" href="#运行方式" aria-label="Permalink to &quot;运行方式&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> 01-todo-app</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">        # Vitest</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test:e2e</span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">  # Playwright</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="学习路径" tabindex="-1">学习路径 <a class="header-anchor" href="#学习路径" aria-label="Permalink to &quot;学习路径&quot;">​</a></h3><ol><li>阅读 <code>src/lib/stores/todoStore.ts</code> — 理解 .svelte.ts 共享状态</li><li>阅读 <code>src/routes/+page.svelte</code> — 理解 Runes 在页面中的使用</li><li>阅读 <code>src/routes/TodoItem.svelte</code> — 理解 Props 和事件</li><li>运行测试 — 理解测试策略</li></ol><h2 id="_02-博客平台" tabindex="-1">02-博客平台 <a class="header-anchor" href="#_02-博客平台" aria-label="Permalink to &quot;02-博客平台&quot;">​</a></h2><h3 id="项目简介-1" tabindex="-1">项目简介 <a class="header-anchor" href="#项目简介-1" aria-label="Permalink to &quot;项目简介&quot;">​</a></h3><p>全栈博客平台，基于 SvelteKit 2。</p><h3 id="技术栈-1" tabindex="-1">技术栈 <a class="header-anchor" href="#技术栈-1" aria-label="Permalink to &quot;技术栈&quot;">​</a></h3><ul><li>SvelteKit 2.53.x</li><li>Svelte 5.53.x</li><li>TypeScript 5.8</li><li>内存数据库（可替换为 SQLite/Drizzle）</li></ul><h3 id="核心功能-1" tabindex="-1">核心功能 <a class="header-anchor" href="#核心功能-1" aria-label="Permalink to &quot;核心功能&quot;">​</a></h3><ul><li>✅ 文件系统路由（/blog/[slug]）</li><li>✅ load 函数（服务端数据获取）</li><li>✅ Form Actions（创建文章 + 验证）</li><li>✅ API 路由（REST API）</li><li>✅ Markdown 渲染</li><li>✅ SEO 优化（SSR）</li></ul><h3 id="文件结构-1" tabindex="-1">文件结构 <a class="header-anchor" href="#文件结构-1" aria-label="Permalink to &quot;文件结构&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>02-blog-platform/</span></span>
<span class="line"><span>├── src/routes/+page.svelte                  # 首页（文章列表）</span></span>
<span class="line"><span>├── src/routes/+page.server.ts               # 首页 load</span></span>
<span class="line"><span>├── src/routes/blog/[slug]/+page.svelte      # 文章详情</span></span>
<span class="line"><span>├── src/routes/blog/[slug]/+page.server.ts   # 文章 load</span></span>
<span class="line"><span>├── src/routes/blog/new/+page.svelte         # 新建文章</span></span>
<span class="line"><span>├── src/routes/blog/new/+page.server.ts      # Form Actions</span></span>
<span class="line"><span>├── src/routes/api/posts/+server.ts          # API 路由</span></span>
<span class="line"><span>├── src/lib/db/posts.ts                      # 数据层</span></span>
<span class="line"><span>└── tests/                                   # 测试</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h3 id="运行方式-1" tabindex="-1">运行方式 <a class="header-anchor" href="#运行方式-1" aria-label="Permalink to &quot;运行方式&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> 02-blog-platform</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">    # 生产构建</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="学习路径-1" tabindex="-1">学习路径 <a class="header-anchor" href="#学习路径-1" aria-label="Permalink to &quot;学习路径&quot;">​</a></h3><ol><li>阅读 <code>src/lib/db/posts.ts</code> — 数据层设计</li><li>阅读 <code>src/routes/+page.server.ts</code> — load 函数</li><li>阅读 <code>src/routes/blog/new/+page.server.ts</code> — Form Actions</li><li>阅读 <code>src/routes/api/posts/+server.ts</code> — API 路由</li></ol><h2 id="_03-dashboard-面板" tabindex="-1">03-Dashboard 面板 <a class="header-anchor" href="#_03-dashboard-面板" aria-label="Permalink to &quot;03-Dashboard 面板&quot;">​</a></h2><h3 id="项目简介-2" tabindex="-1">项目简介 <a class="header-anchor" href="#项目简介-2" aria-label="Permalink to &quot;项目简介&quot;">​</a></h3><p>数据可视化 Dashboard，展示 Svelte Action 和高级组件模式。</p><h3 id="技术栈-2" tabindex="-1">技术栈 <a class="header-anchor" href="#技术栈-2" aria-label="Permalink to &quot;技术栈&quot;">​</a></h3><ul><li>Svelte 5.53.x</li><li>Vite 6.3</li><li>D3.js（通过 Action 集成）</li><li>TypeScript 5.8</li></ul><h3 id="核心功能-2" tabindex="-1">核心功能 <a class="header-anchor" href="#核心功能-2" aria-label="Permalink to &quot;核心功能&quot;">​</a></h3><ul><li>✅ KPI 卡片（$derived 聚合计算）</li><li>✅ SVG 折线图/柱状图/饼图（Action + D3）</li><li>✅ 数据表格（排序、搜索、分页）</li><li>✅ 暗色主题切换</li><li>✅ ResizeObserver Action（响应式图表）</li><li>✅ 模拟实时数据更新</li></ul><h3 id="文件结构-2" tabindex="-1">文件结构 <a class="header-anchor" href="#文件结构-2" aria-label="Permalink to &quot;文件结构&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>03-dashboard-analytics/</span></span>
<span class="line"><span>├── src/routes/+page.svelte              # Dashboard 首页</span></span>
<span class="line"><span>├── src/lib/components/KpiCard.svelte    # KPI 卡片</span></span>
<span class="line"><span>├── src/lib/components/LineChart.svelte  # 折线图</span></span>
<span class="line"><span>├── src/lib/components/BarChart.svelte   # 柱状图</span></span>
<span class="line"><span>├── src/lib/components/DataTable.svelte  # 数据表格</span></span>
<span class="line"><span>├── src/lib/actions/resizeObserver.ts    # Resize Action</span></span>
<span class="line"><span>├── src/lib/stores/dataStore.ts          # 数据存储</span></span>
<span class="line"><span>└── tests/                               # 测试</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h3 id="运行方式-2" tabindex="-1">运行方式 <a class="header-anchor" href="#运行方式-2" aria-label="Permalink to &quot;运行方式&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> 03-dashboard-analytics</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> test</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="学习路径-2" tabindex="-1">学习路径 <a class="header-anchor" href="#学习路径-2" aria-label="Permalink to &quot;学习路径&quot;">​</a></h3><ol><li>阅读 <code>src/lib/actions/resizeObserver.ts</code> — Action 设计</li><li>阅读 <code>src/lib/components/LineChart.svelte</code> — Action + D3 集成</li><li>阅读 <code>src/lib/stores/dataStore.ts</code> — 复杂状态管理</li><li>阅读 <code>src/lib/components/DataTable.svelte</code> — 高级组件模式</li></ol><h2 id="源码位置" tabindex="-1">源码位置 <a class="header-anchor" href="#源码位置" aria-label="Permalink to &quot;源码位置&quot;">​</a></h2><p>所有项目源码位于：<code>../../20-code-lab/20.5-frontend-frameworks/svelte-signals-lab/</code></p><h2 id="相关专题" tabindex="-1">相关专题 <a class="header-anchor" href="#相关专题" aria-label="Permalink to &quot;相关专题&quot;">​</a></h2><table tabindex="0"><thead><tr><th>学习阶段</th><th>推荐阅读</th></tr></thead><tbody><tr><td>入门</td><td><a href="/svelte-signals-stack/02-svelte-5-runes">Svelte 5 Runes 深度指南</a></td></tr><tr><td>语法</td><td><a href="/svelte-signals-stack/12-svelte-language-complete">Svelte 语言完全参考</a></td></tr><tr><td>组件</td><td><a href="/svelte-signals-stack/13-component-patterns">组件开发模式大全</a></td></tr><tr><td>全栈</td><td><a href="/svelte-signals-stack/03-sveltekit-fullstack">SvelteKit 全栈框架</a></td></tr><tr><td>原理</td><td><a href="/svelte-signals-stack/14-reactivity-deep-dive">响应式系统深度原理</a></td></tr><tr><td>学习路径</td><td><a href="/svelte-signals-stack/16-learning-ladder">渐进式学习阶梯</a></td></tr></tbody></table><blockquote><p>最后更新: 2026-05-01</p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("code-lab/svelte-signals-lab.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const svelteSignalsLab = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  svelteSignalsLab as default
};
